[2025-03-21T03:27:31.703+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T03:27:31.718+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_to_postgres_dag.run_spark_processing manual__2025-03-21T03:27:31.463237+00:00 [queued]>
[2025-03-21T03:27:31.725+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_to_postgres_dag.run_spark_processing manual__2025-03-21T03:27:31.463237+00:00 [queued]>
[2025-03-21T03:27:31.726+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-21T03:27:31.739+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_spark_processing> on 2025-03-21 03:27:31.463237+00:00
[2025-03-21T03:27:31.746+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=339) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-21T03:27:31.747+0000] {standard_task_runner.py:72} INFO - Started process 340 to run task
[2025-03-21T03:27:31.746+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spark_to_postgres_dag', 'run_spark_processing', 'manual__2025-03-21T03:27:31.463237+00:00', '--job-id', '2304', '--raw', '--subdir', 'DAGS_FOLDER/DAG_spark_to_postgres.py', '--cfg-path', '/tmp/tmp1cthqxnz']
[2025-03-21T03:27:31.748+0000] {standard_task_runner.py:105} INFO - Job 2304: Subtask run_spark_processing
[2025-03-21T03:27:31.761+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-21T03:27:31.795+0000] {task_command.py:467} INFO - Running <TaskInstance: spark_to_postgres_dag.run_spark_processing manual__2025-03-21T03:27:31.463237+00:00 [running]> on host d89ac10847cd
[2025-03-21T03:27:31.859+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_to_postgres_dag' AIRFLOW_CTX_TASK_ID='run_spark_processing' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T03:27:31.463237+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T03:27:31.463237+00:00'
[2025-03-21T03:27:31.860+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-21T03:27:31.908+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/DAG_spark_to_postgres.py", line 12, in run_spark_script
    subprocess.run(["python", "/opt/airflow/dags/helpers/pyspark_dataproc.py"], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '/opt/airflow/dags/helpers/pyspark_dataproc.py']' returned non-zero exit status 1.
[2025-03-21T03:27:31.917+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=spark_to_postgres_dag, task_id=run_spark_processing, run_id=manual__2025-03-21T03:27:31.463237+00:00, execution_date=20250321T032731, start_date=20250321T032731, end_date=20250321T032731
[2025-03-21T03:27:31.926+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-21T03:27:31.927+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 2304 for task run_spark_processing (Command '['python', '/opt/airflow/dags/helpers/pyspark_dataproc.py']' returned non-zero exit status 1.; 340)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/DAG_spark_to_postgres.py", line 12, in run_spark_script
    subprocess.run(["python", "/opt/airflow/dags/helpers/pyspark_dataproc.py"], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '/opt/airflow/dags/helpers/pyspark_dataproc.py']' returned non-zero exit status 1.
[2025-03-21T03:27:31.962+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-21T03:27:31.976+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T03:27:31.979+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
