[2025-03-21T04:17:09.442+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T04:17:09.461+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_to_postgres_dag.run_spark_processing manual__2025-03-21T04:17:08.906397+00:00 [queued]>
[2025-03-21T04:17:09.468+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_to_postgres_dag.run_spark_processing manual__2025-03-21T04:17:08.906397+00:00 [queued]>
[2025-03-21T04:17:09.469+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-21T04:17:09.481+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_spark_processing> on 2025-03-21 04:17:08.906397+00:00
[2025-03-21T04:17:09.488+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=229) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-21T04:17:09.487+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spark_to_postgres_dag', 'run_spark_processing', 'manual__2025-03-21T04:17:08.906397+00:00', '--job-id', '2306', '--raw', '--subdir', 'DAGS_FOLDER/DAG_spark_to_postgres.py', '--cfg-path', '/tmp/tmp5ag85vy9']
[2025-03-21T04:17:09.490+0000] {standard_task_runner.py:72} INFO - Started process 230 to run task
[2025-03-21T04:17:09.490+0000] {standard_task_runner.py:105} INFO - Job 2306: Subtask run_spark_processing
[2025-03-21T04:17:09.511+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-21T04:17:09.552+0000] {task_command.py:467} INFO - Running <TaskInstance: spark_to_postgres_dag.run_spark_processing manual__2025-03-21T04:17:08.906397+00:00 [running]> on host d89ac10847cd
[2025-03-21T04:17:09.630+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_to_postgres_dag' AIRFLOW_CTX_TASK_ID='run_spark_processing' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T04:17:08.906397+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T04:17:08.906397+00:00'
[2025-03-21T04:17:09.631+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-21T04:17:09.649+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-21T04:17:09.650+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/helpers/pyspark_dataproc.py']
[2025-03-21T04:17:09.658+0000] {subprocess.py:99} INFO - Output:
[2025-03-21T04:17:09.692+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-21T04:17:09.692+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/helpers/pyspark_dataproc.py", line 1, in <module>
[2025-03-21T04:17:09.693+0000] {subprocess.py:106} INFO -     from pyspark.sql import SparkSession
[2025-03-21T04:17:09.693+0000] {subprocess.py:106} INFO - ModuleNotFoundError: No module named 'pyspark'
[2025-03-21T04:17:09.695+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-21T04:17:09.703+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-21T04:17:09.711+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_to_postgres_dag, task_id=run_spark_processing, run_id=manual__2025-03-21T04:17:08.906397+00:00, execution_date=20250321T041708, start_date=20250321T041709, end_date=20250321T041709
[2025-03-21T04:17:09.724+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-21T04:17:09.724+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 2306 for task run_spark_processing (Bash command failed. The command returned a non-zero exit code 1.; 230)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-21T04:17:09.746+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-21T04:17:09.761+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T04:17:09.762+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
